source:              .
destination:         ./_site
includes:            ./_includes
# markdown:            CommonMarkGhPages
# markdown:            gfm
highlight:           pygments
disqus_username:     disqus_OlGnKMzoKF

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Vivek Shrinivasan
tagline:             I ♡ building products
url:                 https://kaizer1v.github.com
baseurl:             ""

plugins:             [jekyll-paginate]
paginate:            50
paginate_path:       "/archives/page/:num"

## Excerpt Separator
excerpt_separator:   <!--more-->

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  style: :compressed
  load_paths:
    - node_modules/bootstrap/scss
    - _sass

# About/contact
author:
  name:              Vivek Shrinivasan
  url:               https://kaizer1v.github.io
  email:             kaizer1v

# Custom vars
version:             2.4.0
github:
  repo:              https://github.com/kaizer1v/kaizer1v.github.io

# Collections
collections_dir: all_collections

collections:
  interaction_design:
    permalink: /:collection/:name
    output: true
  projects:
    permalink: /:collection/:name
    output: true
  experiments:
    permalink: /:collection/:name
    output: true

# Default settings for templates
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      comments: false
  - scope:
      path: ""
      type: "experiments"
    values:
      layout: "experiment"
      comments: false

# Includes an icon in the footer for each username you enter
links:
  organisation:
    name: CivicDataLab
    link: https://www.civicdatalab.in
  resume: https://github.com/kaizer1v/json-resume/raw/master/removethis/Vivek_Shrinivasan_Resume.pdf
  email:             kaizer1v@gmail.com
  github:            https://github.com/kaizer1v
  linkedin:          https://in.linkedin.com/in/vivek-shrinivasan-b67a4121
  rss: # just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter:           https://twitter.com/kaizer1v
  stackoverflow:     https://stackoverflow.com/users/831295/kaizer1v
  dribbble:
  facebook:
  flickr:            https://www.flickr.com/photos/10583297@N03/
  instagram:
  pinterest:
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/
