pygments:						 true

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Vivek Shrinivasan
tagline:             Carpe Diem
url:                 https://kaizer1v.github.com
baseurl:             ""

paginate:            1

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Vivek Shrinivasan
  url:               https://twitter.com/kaizer1v
  email:             kaizer1v

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/kaizer1v

# This is the list of pages to include in the header of the website.
pages_list:       
  About: '/about/'